---
title:  "Space syntax"
layout: post
hashtag: "#informatin #visualization"
comment: true
thumbnail: /img/space-syntax-5.png
---

<div id="toc"></div>
<h3>Depth of space</h3>
<div style='text-align: justify;'>

    The depth of spcae can be a criterion for evaluating the <code>accessibility</code> of the space.
    Let's take a look at the image below. There are two spaces, and the way they are all laid out is the same.
    However, you can see that the accessibility to the space changes depending on the way the spaces are connected, that is, the depth.
    
    <!--break-->
    <figure>
        <img src="../img/space-syntax-0.png" style="width: 60%; display: block; margin-left: auto; margin-right: auto;">
        <figcaption style="text-align: center; margin-top: 1em">Same space different evaluation 
            <br>From the top, space structure · space connection
        </figcaption>
    </figure>
    <br>

    Let's take a look at a little more complex structure of space. 
    We have 2 spaces, each space consists of 8 rooms. We can visualize the conditions of each space as follows. (The room number 0 is entrance)
    <br><br>
    At first glance, there is no difference between the two spaces. However, the difference becomes clear when looking at the <code>graph</code> and <a href="https://github.com/PARKCHEOLHEE-lab/ToyProjects/blob/master/space_syntax/graph_node.py#L47-L73">calculated depth</a> in the picture on the right.
    Interestingly, even if the space (Space 1: 8, Space 2: 7) is in the same location, the depth varies according to the location of the entrance and the connected relationship.
    This can be seen through the computed depth on the far right. The <code>maximum depths of the two spaces are 6 and 2</code>, respectively.
    <figure>
        <img src="../img/space-syntax-1.png" style="width: 80%; display: block; margin-left: auto; margin-right: auto;">
        <figcaption style="text-align: center; margin-top: 1em">The conditions of each space 
            <br>From the top, Space 1 · Space 2
        </figcaption>
    </figure>
</div>

<br>

<h3>Evaluating each space</h3>
<div style='text-align: justify;'>

    Visibility polygons are the criterion for evaluating the visibility at a specific point.
    This can be used to quantitatively evaluate spatial activity or connectivity. Let's evaluate the previous two spaces through the following process.
    <figure>
        <img src="../img/space-syntax-2.png" style="width: 80%; display: block; margin-left: auto; margin-right: auto;">
        <figcaption style="text-align: center; margin-top: 1em">What is the visibility polygon ?
            <br>From the left, Obstacles · Visibility polygon
        </figcaption>
    </figure>
    <br>
    First, we need to create a bounding box to wrap the all space. And then write a square grid in the bounding box.
    Second, creates the center point of all grids, and checks whether the point is located inside the space or outisde.
    Lastly, create a visibility polygon through point in space. And measure the peremeter of the polygon. You can check the process through the 
    <a href="https://github.com/PARKCHEOLHEE-lab/ToyProjects/blob/master/space_syntax/space_syntax.py">link.</a>
    <figure>
        <img src="../img/space-syntax-3.png" style="width: 45%; display: block; margin-left: auto; margin-right: auto;">
        <figcaption style="text-align: center; margin-top: 1em">Apply to the space 2
        </figcaption>
    </figure>
    <br>

    If you put the perimeter of the polygon obtained earlier in the list and match it with the index of the grid to brightly visualize the wide perimeter, the image below is created.
    <figure>
        <img src="../img/space-syntax-4.png" style="width: 70%; display: block; margin-left: auto; margin-right: auto;">
        <figcaption style="text-align: center; margin-top: 1em">Space syntax
        </figcaption>
    </figure>

    <br><br>

<pre><code class="python">
    import math
    import random
    import Rhino.Geometry as rg
    import Rhino.RhinoDoc as rc
    import rhinoscriptsyntax as rs
    import ghpythonlib.components as gh
    import Rhino

    class Space:
        def __init__(self, curves, resolution):
            self.curves = curves
            self.resolution = resolution
            self.coordinate = self.get_coordinate()
            self.grid = self.generate_grid()
            
        def get_coordinate(self):
            points = []
            for curve in self.curves:
                points.extend(rs.CurvePoints(curve))
            
            min_coords = []
            max_coords = []
            for i in range(2):
                min_coord = min([coord[i] for coord in list(set(points))])
                max_coord = max([coord[i] for coord in list(set(points))])
                min_coords.append(min_coord)
                max_coords.append(max_coord)
            
            min_x, min_y = min_coords
            max_x, max_y = max_coords
            coordinates = [rg.Point3d(min_x, min_y, 0),
                        rg.Point3d(max_x, min_y, 0),
                        rg.Point3d(min_x, max_y, 0),
                        rg.Point3d(max_x, max_y, 0)]
            return coordinates
            
        def generate_brep(self):
            path = rs.AddLine(rs.AddPoint(0,0,0), rs.AddPoint(0,0,-0.1))
            surface = rs.AddPlanarSrf(self.curves)
            brep = rs.ExtrudeSurface(surface, path)
            return rs.coercebrep(brep)
            
        def generate_boundingbox(self):
            plane = rg.Plane.WorldXY
            return rg.Rectangle3d(plane, self.coordinate[0], self.coordinate[3])
            
        def generate_grid(self):
            bbox_width = self.coordinate[0].DistanceTo(self.coordinate[1])
            bbox_height = self.coordinate[0].DistanceTo(self.coordinate[2])
            unit_width = bbox_width / self.resolution
            unit_height= bbox_height / self.resolution
            start_point = self.coordinate[0]
            
            grid = []
            for i in range(resolution):
                for j in range(resolution):
                    origin = [start_point[0] + i*unit_width, start_point[1] + j*unit_height, start_point[2]]
                    unit = rs.AddRectangle(origin, unit_width, unit_height)
                    grid.append(unit)
            return grid
            
        def generate_centroid(self):
            grid = self.generate_grid()
            centroids = [rs.CurveAreaCentroid(unit)[0] for unit in grid]
            return centroids
            
        def generate_ray(self):
            centroids = self.generate_centroid()
            rays = []
            for centroid in centroids:
                ray_len = rg.Point3d(100,0,0)
                ray = rs.AddLine(centroid, centroid + ray_len)
                rays.append(ray)
            return rays
            
        def generate_inside_grid(self):
            brep = self.generate_brep()
            centroids = self.generate_centroid()
            inside_check = gh.PointInBrep(brep, centroids, False)
            inside_grid = []
            inside_centroid = []
            for i, check in enumerate(inside_check):
                if check == True:
                    inside_grid.append(self.grid[i])
                    inside_centroid.append(centroids[i])
            return inside_grid, inside_centroid
            
        def generate_grid_surface(self):
            inside_grid = [rs.coercecurve(unit) for unit in self.generate_inside_grid()[0]]
            return gh.BoundarySurfaces(inside_grid)
            
        def generate_vispolygon(self):
            inside_centroid = self.generate_inside_grid()[1]
            point_count = 100
            radius = 100
            vispolygons = []
            for centroid in inside_centroid:
                isovist = gh.IsoVist(centroid, point_count, radius, self.curves)[0]
                vispolygons.append(gh.PolyLine(isovist, True))
            return vispolygons
            
        def perimeter_vispolygon(self):
            vispolygons = self.generate_vispolygon()
            perimeters = []
            for vispolygon in vispolygons:
                perimeters.append(rs.CurveLength(vispolygon))
            return perimeters
            


    if __name__ == "__main__":
        space_obj = Space(space, resolution)
        
        all_perimeter = space_obj.perimeter_vispolygon()
        min_perimeter = min(space_obj.perimeter_vispolygon())
        max_perimeter = max(space_obj.perimeter_vispolygon())
        grid_surface = space_obj.generate_grid_surface()
</code></pre>
    
</div>
<br><br>