---
title:  "Dynamic mesh fence"
layout: post
featured: false
hashtag: "#formfollowsfunction"
comment: true
thumbnail: https://user-images.githubusercontent.com/83874157/203985300-3e5ed9fa-9b17-41a9-9fc0-5c43f32e035b.png
---

<div id="toc"></div>
<h3>Where does design start ?</h3>
<div style='text-align: justify;'>

Different designers have different approaches to solving design problems. Intuition, aesthetics, <code>function</code>, cost, data, structure, etc. are prioritized based on what designers value. And this is expressed in form. A perfect design has each element properly balanced. However, it is not easy to do such a design in reality. So, in general, we set one or two high priorities and design according to the conditions.

<br><br>
<!--break-->
In my opinion, what should be most important is what you can base your analysis on: function, data, structure. Designers are persuaders. We have an obligation to inform the client of how the design came about. To do that, the logic in the design process must be solid, and this logic comes from the elements listed above. In other words, <code>design is what must necessarily be so</code> in the process.

<!-- 
디자인 문제를 해결하는 접근방식은 디자이너마다 다릅니다. 또한 직관, 심미, 기능, 비용, 데이터 등의 우선순위는 디자이너가 무엇을 중요하게 여기는지에 따라 결정됩니다. 그리고 이것은 형태로 발현됩니다. 완벽한 디자인은 각각의 요소들이 적절하게 균형을 갖추고 있습니다. 하지만 현실적으로 그런 디자인을 하기는 쉽지 않습니다. 그래서 우리는 일반적으로 한 두가지 정도의 높은 우선순위를 정하고 그에 맞는 조건으로 디자인을 합니다.

제 생각에 가장 중요시 되어야 하는 것은, 기능, 데이터, 구조와 같은 분석에 기반할 수 있는 요소들입니다. 디자이너는 설득자입니다. 우리는 클라이언트에게 디자인이 이렇게 된 과정을 알려야 할 의무가 있습니다. 그러려면 디자인 과정에서의 논리가 탄탄해야 하고, 이러한 논리는 위에서 나열한 요소들로부터 나옵니다. 즉 디자인은 그 과정에서 필연적으로 그렇게 되어야만 하는것입니다.
-->

</div>

<br>

<!-- <img src="https://user-images.githubusercontent.com/83874157/203311006-a39a4e44-7a09-4744-a303-805ad562a82b.png" style="max-width:20%; height:auto; padding-left: 45px; padding-top: 20px;" align="right"/> -->
<h3>Form follows function</h3>
<div style="text-align: center;">
    <figure>
        <img src="https://user-images.githubusercontent.com/83874157/203985300-3e5ed9fa-9b17-41a9-9fc0-5c43f32e035b.png" style="width:auto; height:auto;">
        <figcaption style="text-align: center">Mesh fence variation
          <br>From the left, orignal · rack · futsal · bench</figcaption>
      </figure>
</div>
<br>

<div style='margin-top: 15px; text-align: justify;'>

That's why I like designs where form follows function. This project is to <code>create an algorithm</code> from this point of view. <code>Mesh fence</code> is a product that is common in our surroundings and is faithful to its function. A mesh fence divides the boundary between here and there and <code>blocks interaction</code>

<br><br>

I thought it would be possible to maintain the blocking function needed inside the boundary, and create interaction between internal users as an additional function through internal transformation. I will be able to give users the necessary functions by bending the fence to create a bench or a stand for flower pots.

<br><br>

Please refer to <a href="https://github.com/PARKCHEOLHEE-lab/fff/tree/main/mesh_fence">this link</a> to download the prototype.

<br><br>

<pre><code class="python">
    import Rhino.Geometry as rg
    import rhinoscriptsyntax as rs
    import ghpythonlib.components as gh
    import ghpythonlib.treehelpers as gt


    FENCE_INTERVAL = 20.9
    FENCE_COLUMN_RADIUS = 0.38
    FENCE_GRID_COUNT = 32
    FENCE_HEIGHT = 17
    FENCE_Y_VECTOR = rg.Point3d(0, -FENCE_HEIGHT / 4, 0)
    FENCE_Z_VECTOR = rg.Point3d(0, 0, FENCE_HEIGHT)
    FENCE_Y_EXTRUDE = rg.Point3d(0, 5, 0)

    TOLERANCE = 0.001

    def is_close(a, b, tol=TOLERANCE):
        if abs(a - b) < tol:
            return True
        return False

    class DynamicMeshFence:
        def __init__(self, fence_count, directions, shape):
            self.fence_count = fence_count
            self.generate(directions, shape)
            
        def generate(self, directions, shape):
            """generate dynamic mesh fence"""
            
            self.get_directions(directions)
            self.get_merged_input_shapes(shape)
            self.get_fence_columns()
            self.get_fence_base_geoms()
            self.get_clean_trimmed_shapes()
            self.get_merged_trimmed_shapes()
            self.get_fence_contour_lines()
            
            if self.merged_trimmed_shapes is None:
                self.result_mesh_fence = gt.list_to_tree(self.fence_faces_contour_lines)
                
            else:
                self.get_splitted_fence_contour_lines()
                self.get_result_mesh_fence()
                self.result_mesh_fence = gt.list_to_tree(self.result_mesh_fence)
                
        def get_directions(self, directions):
            """calculate trim directions"""
            self.directions = directions
            if len(directions) != self.fence_count:
                diff_directions_count = abs(len(directions) - self.fence_count)
                self.directions = directions[:diff_directions_count] + [directions[-1]] * (diff_directions_count + 1)
            
        def get_merged_input_shapes(self, shape):
            """union & merge input brep shapes"""
            
            if len(shape) == 0 or all(s is None for s in shape):
                shape = gh.Sphere(rg.Point3d(0, 0, 500), 1)  # dummy shape
                    
            union_shape = gh.SolidUnion(shape)
            if isinstance(union_shape, rg.Brep):
                union_shape = [union_shape]
            
            merged_shape = rg.Brep.MergeBreps(union_shape, TOLERANCE)
            self.shape = merged_shape
            
        def get_fence_columns(self):
            """generate fence columns"""
                        
            self.fence_origin = []         # List[List[Point3d]]
            self.fence_columns = []        # List[Brep]
            
            for n in range(self.fence_count + 1):
                origin = rg.Point3d(n * FENCE_INTERVAL, 0, 0)
                self.fence_origin.append(origin)
                
                column_base = rg.Circle(origin, FENCE_COLUMN_RADIUS)
                column = gh.Extrude(column_base, FENCE_Z_VECTOR)
                column = column.CapPlanarHoles(0.001)
                
                self.fence_columns.append(column)
                
        def get_fence_base_geoms(self):
            """generate base geometries for dynamic mesh fence"""

            self.trimmed_shapes = []         # List[Brep]
            self.fence_faces = []            # List[Brep]
            self.extruded_fence_faces = []   # List[Brep]
            self.adjusted_origin = []        # List[List[Point3d]]
            
            for i, direction in zip(range(len(self.fence_origin) - 1), self.directions):
                curr_origin = self.fence_origin[i]
                next_origin = self.fence_origin[i+1]
                
                adjusted_curr_origin = curr_origin + rg.Point3d(FENCE_COLUMN_RADIUS, 0, 0)
                adjusted_next_origin = next_origin + rg.Point3d(-FENCE_COLUMN_RADIUS, 0, 0)
                self.adjusted_origin.append([adjusted_curr_origin, adjusted_next_origin])
                
                fence_base_line = rg.Line(adjusted_curr_origin, adjusted_next_origin)
                fence_face = gh.Extrude(fence_base_line, FENCE_Z_VECTOR)
                self.fence_faces.append(fence_face)
                
                scaled_fence_face = gh.Scale(fence_face, gh.Area(fence_face).centroid, 0.95).geometry
                scaled_fence_face_extrusion = gh.Extrude(scaled_fence_face, FENCE_Y_VECTOR)
                if direction:
                    scaled_fence_face_extrusion = gh.Extrude(scaled_fence_face, -FENCE_Y_VECTOR)
                    
                self.extruded_fence_faces.append(scaled_fence_face_extrusion)
                
                each_trimmed_shapes = rg.Brep.CreateBooleanIntersection(scaled_fence_face_extrusion, self.shape, TOLERANCE)
                self.trimmed_shapes.extend(each_trimmed_shapes)
                
        def get_clean_trimmed_shapes(self):
            """remove shapes not intersecting fence face"""
            
            self.result_trimmed_shapes = []  # List[Brep]
            merged_fence_faces = rg.Brep.MergeBreps(self.fence_faces, TOLERANCE)
            
            for each_trimmed_shape in self.trimmed_shapes:
                is_intsc_shape = gh.BrepXBrep(each_trimmed_shape, merged_fence_faces).curves
                if is_intsc_shape is not None:
                    self.result_trimmed_shapes.append(each_trimmed_shape)
                    
        def get_merged_trimmed_shapes(self):
            self.merged_trimmed_shapes = rg.Brep.MergeBreps(self.result_trimmed_shapes, TOLERANCE)
                    
        def get_fence_contour_lines(self):
            """generate base fence lines & trimmed shapes contour lines"""
            
            self.fence_faces_contour_lines = []  # List[]
            self.trimmed_shapes_contour_lines = []
            
            for (start_origin, end_origin), fence_face in zip(self.adjusted_origin, self.fence_faces):
                # generate each fence face contour lines
                each_face_contour_lines = rg.Brep.CreateContourCurves(fence_face, 
                                                                    start_origin, 
                                                                    end_origin, 
                                                                    FENCE_INTERVAL / FENCE_GRID_COUNT)[1:]
                                                                    
                each_face_contour_lines_z = rg.Brep.CreateContourCurves(fence_face, 
                                                                        rg.Point3d(0,0,FENCE_HEIGHT), 
                                                                        rg.Point3d(0,0,0), 
                                                                        FENCE_HEIGHT / FENCE_GRID_COUNT * 2.5)
                                                                        
                self.fence_faces_contour_lines.append(each_face_contour_lines + each_face_contour_lines_z)
                
                if self.merged_trimmed_shapes is None:
                    continue
                
                # generate each shape contour lines
                merged_shapes_contour_lines = rg.Brep.CreateContourCurves(self.merged_trimmed_shapes, 
                                                                        start_origin, 
                                                                        end_origin, 
                                                                        FENCE_INTERVAL / FENCE_GRID_COUNT)
                
                simplified_each_shape_contour_lines = gh.SimplifyCurve(merged_shapes_contour_lines).curve
                
                if simplified_each_shape_contour_lines is None:
                    self.trimmed_shapes_contour_lines.append(each_face_contour_lines + each_face_contour_lines_z)
                    continue
                
                if isinstance(simplified_each_shape_contour_lines, rg.PolyCurve):
                    simplified_each_shape_contour_lines = [simplified_each_shape_contour_lines]
                
                exploded_each_shape_contour_lines = []
                for shape_contour_line in simplified_each_shape_contour_lines:
                    exploded_contour_lines = rg.PolylineCurve.DuplicateSegments(shape_contour_line)
                    exploded_each_shape_contour_lines.extend(exploded_contour_lines)
                    
                merged_shapes_contour_lines_z = rg.Brep.CreateContourCurves(self.merged_trimmed_shapes,  
                                                                            rg.Point3d(0,0,FENCE_HEIGHT), 
                                                                            rg.Point3d(0,0,0), 
                                                                            FENCE_HEIGHT / FENCE_GRID_COUNT * 2.5)
                                                                        
                simplified_each_shape_contour_lines_z = gh.SimplifyCurve(merged_shapes_contour_lines_z).curve
                
                exploded_each_shape_contour_lines_z = []
                for shape_contour_line_z in simplified_each_shape_contour_lines_z:
                    exploded_contour_lines_z = rg.PolylineCurve.DuplicateSegments(shape_contour_line_z)
                    exploded_each_shape_contour_lines_z.extend(exploded_contour_lines_z)
                    
                each_result_contour_lines = []
                for exploded_contour_line in exploded_each_shape_contour_lines:
                    start_pt = exploded_contour_line.PointAtStart
                    end_pt = exploded_contour_line.PointAtEnd
                    if not is_close(0, start_pt.Y) or not is_close(0, end_pt.Y):
                        each_result_contour_lines.append(exploded_contour_line)
                    
                each_result_contour_lines_z = []
                for exploded_contour_line_z in exploded_each_shape_contour_lines_z:
                    start_pt_z = exploded_contour_line_z.PointAtStart
                    end_pt_z = exploded_contour_line_z.PointAtEnd
                    if not is_close(0, start_pt_z.Y) or not is_close(0, end_pt_z.Y):
                        each_result_contour_lines_z.append(exploded_contour_line_z)
                
                self.trimmed_shapes_contour_lines.append(each_result_contour_lines + each_result_contour_lines_z)
                
        def get_splitted_fence_contour_lines(self):
            """generate splitted fence faces contour lines"""
            self.splitted_original_fence_lines = []
            for each_original_lines in self.fence_faces_contour_lines:
                each_splitted_original_fence_lines = []
                
                for original_line in each_original_lines:
                    splitted_original_lines = original_line.Split(self.merged_trimmed_shapes, TOLERANCE)
                    
                    if len(splitted_original_lines) == 0:
                        each_splitted_original_fence_lines.append(original_line)
                        continue
                        
                    else:
                        each_splitted_original_fence_lines.extend(splitted_original_lines)
                        
                self.splitted_original_fence_lines.append(each_splitted_original_fence_lines)
                
        def get_result_mesh_fence(self):
            """generate result"""
            
            self.result_mesh_fence = []
            
            for each_splitted_original_fence_lines, each_contour_lines in zip(self.splitted_original_fence_lines, 
                                                                            self.trimmed_shapes_contour_lines):
                                                                                
                each_splitted_original_fence_lines_centroids = gh.CurveMiddle(each_splitted_original_fence_lines)
                pattern = gh.PointInBreps(self.merged_trimmed_shapes, each_splitted_original_fence_lines_centroids, False).index
                negative_pattern = gh.Negative(pattern)
                fence_lines = gh.CullPattern(each_splitted_original_fence_lines, negative_pattern)
                
                result = gh.JoinCurves(fence_lines + list(each_contour_lines), False)
                self.result_mesh_fence.append(result)


    if __name__ == "__main__":
        
        dynamic_mesh_fence = DynamicMeshFence(fence_count, directions, shape)
        fence_columns = dynamic_mesh_fence.fence_columns
        result_mesh_fence = dynamic_mesh_fence.result_mesh_fence
</code></pre>

</div>

<br><br>
